# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Semestre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
                ('semestre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Semestre.Semestre')),
            ],
        ),
    ]
