# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('age', models.IntegerField(null=True)),
                ('apogee', models.IntegerField(null=True)),
                ('date_naissance', models.DateField(null=True)),
                ('sexe', models.CharField(max_length=1, null=True)),
                ('adresse', models.CharField(max_length=100, null=True)),
                ('ine', models.CharField(max_length=100, null=True)),
                ('adresse_parents', models.CharField(max_length=100, null=True)),
                ('tel', models.IntegerField(null=True)),
                ('tel_par', models.IntegerField(null=True)),
                ('lieu_naissance', models.CharField(max_length=100, null=True)),
                ('nationalite', models.CharField(max_length=100, null=True)),
                ('situation_familiale', models.CharField(max_length=100, null=True)),
                ('situation_militaire', models.CharField(max_length=100, null=True)),
                ('cate_socio_pro_chef_famille', models.CharField(max_length=100, null=True)),
                ('cate_socio_pro_autre_parent', models.CharField(max_length=100, null=True)),
                ('aide_financiere', models.CharField(max_length=100, null=True)),
                ('bourse', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='etu',
            name='gr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Etudiant.Groupe'),
        ),
    ]
