# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Groupe', '__first__'),
        ('Etudiant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etu',
            name='gr',
        ),
        migrations.AddField(
            model_name='etu',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Groupe.Groupe'),
        ),
        migrations.DeleteModel(
            name='Groupe',
        ),
    ]
