# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
                ('coefficient', models.FloatField(default=1.0)),
                ('unite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UE.UniteE')),
            ],
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Matiere.Matiere'),
        ),
        migrations.AddField(
            model_name='Matiere',
            name='unite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UE.UniteE'),
        ),
    ]
