# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matiere', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='matiere',
        ),
        migrations.DeleteModel(
            name='Enseignant',
        ),
    ]
