# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diplome', '0001_initial'),
        ('Semestre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='diplome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Diplome.Diplome'),
        ),
    ]
